### PR TITLE
Update to v2022-01-20

### LINKED ISSUE #41: New RSS-Bridge version
Hi,

there is a new release version:
https://github.com/RSS-Bridge/rss-bridge/releases/tag/2022-01-20

You should update.

### PR DESCRIPTION
**Pull request by lapineige**
Version 2022-01-20 is available.
https://github.com/RSS-Bridge/rss-bridge/releases/tag/2022-01-20

Fix #41 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!gogogadgetoci

**Comment by lapineige** [comment]
@JimboJoe for some reason I can't tag you to ask for review… Can you please take a look (one CI is finished) ? 🙂

**Comment by lapineige** [comment]
Oh yeah, that package isn't auto-updating yet 😅

**Comment by lapineige** [comment]
CI server is not working right now, so I can't check if it went well :sweat_smile:

**Comment by lapineige** [comment]
!testme

**Comment by yalh76** [comment]
> I'll have a test then. But I can already tell you you missed the README update 😉

The readme will automagically update when the PR will be merged in the YunoHost-Apps organisation

**Comment by JimboJoe** [comment]
So do we need to merge that one or rather try to merge the Testing branch with auto-update... ? 🤔

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
