### PR TITLE
Testing (new permissions)

### PR DESCRIPTION
**Pull request by lapineige**
#33 #31

### CODE REVIEW

**Comment by lapineige** [comment]
Do we need to test this ? Last CI (with only those commits) was fine.

**Comment by JimboJoe** [comment]
maybe wait for #35 ? :grinning:

**Comment by JimboJoe** [comment]
!testme

**Comment by JimboJoe** [comment]
Please note that I've tested it on my production server beforehand and that there's no data to loose in this app 😉

**Comment by lapineige** [comment]
Yeah, that makes thing even easier :D
(That was not criticism FYI ;)

**Pull request merged**
