### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by alexAubin**
Randomly passing by because this page is guilty of the crime of still using "yunohost app checkurl" ... which might break the package in 3.8 (btw this Fixes https://github.com/YunoHost-Apps/rss-bridge_ynh/issues/8 )

Made some other small improvements though there would be many other stuff to do to make the package really shiny (e.g. using ynh_setup_source...)

(Not sure why so many commits in the diff ... looks like testing / master where not synced?)

N.B. : not tested :[

### CODE REVIEW

**Comment by lapineige** [comment]
Thanks for that :)

**Comment by alexAubin** [comment]
Bump (note that the app is now being downgraded to level 4 because of the use of checkurl which has been deprecated for something like 3-4 years)

**Comment by lapineige** [comment]
I can't merge it, sorry. It looks good to me.

**Comment by alexAubin** [comment]
Test ongoing at https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/rss-bridge_ynh%20(aleks)/lastBuild/console

**Pull request merged**
